#!/bin/bash --login
cd $(dirname $0)/../..

export PIPENV_VENV_IN_PROJECT=true
export PIPENV_DEFAULT_PYTHON_VERSION=2.7
export PIPENV_SHELL_FANCY=true
export PIPENV_CACHE_DIR="${TMPDIR}pipenv_cache"

ENV_FILE=".env"
if [ -f "${ENV_FILE}" ]; then
   echo "sourcing .env file"
   source "${ENV_FILE}"
fi

which pipenv
if [ $? != 0 ]
then
  echo "Missing prerequisite pipenv, bailing out"
  exit 1
fi


pipenv --venv
if [ $? != 0 ]
then
  echo "Creating virtualenv for towerlib"
  pipenv install --dev
fi
