#!/bin/bash --login
cd $(dirname $0)/../..

. _CI/scripts/bootstrap
set -e

# locking dependencies
echo "Locking pipenv dependencies"
pipenv lock

echo "Creating requirements.txt"
./_CI/bin/create_requirements.py default

echo "Creating dev-requirements.txt"
./_CI/bin/create_requirements.py develop
