#!/bin/bash --login
cd $(dirname $0)/../..

. _CI/scripts/bootstrap

rm -f docs/test_docs.rst
rm -f docs/modules.rst
rm -rf _build docs/_build

echo "Running make docs.."

pipenv run make -C docs html && \
mv -v docs/_build _build
EXIT_CODE=$?
if ([ "${EXIT_CODE}" != 0 ])
then
    echo "Failed building documentation"
    exit "${EXIT_CODE}"
fi
open _build/html/index.html 2> /dev/null || xdg-open _build/html/index.html 2> /dev/null
