#!/bin/bash --login
cd $(dirname $0)/../..

. _CI/scripts/build

pipenv run twine upload dist/* \
                        -u "${PYPI_UPLOAD_USER}" \
                        --skip-existing \
                        --repository-url https://upload.pypi.org/legacy/
